### ISSUE TITLE
QueueDownloadInProgressException: queue download is already in progress

### ISSUE THREAD

**Issue by keshavmix** [majidgolshadi/Android-Download-Manager-Pro#54]
Hi

I am downloading 2 files by below method.
`dm.startQueueDownload(1, QueueSort.oldestFirst);`

Then, I am disconnecting internet and trying to start queue again but it is throwing 

```
com.golshadi.majid.report.exceptions.QueueDownloadInProgressException: queue download is already in progress
        at com.golshadi.majid.core.DownloadManagerPro.startQueueDownload(DownloadManagerPro.java:182)
```

Please help me to resume queue again..

Thanks

**Comment by majidgolshadi** [comment]
Hello 
This exception happens when the download task stay at "downloading state" so to solve this issue you can change that task state to "pause".(diagram)
To do this you can call pauseQueueDownload method I recommend you to use this method when you get internet disconnect event in your application.
